-- Expand and harden CRM event tracking for advanced correlation analytics
-- Safe migration: all statements are IF NOT EXISTS compatible where possible

CREATE TABLE IF NOT EXISTS crm_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type TEXT NOT NULL,
    user_id UUID NULL REFERENCES profiles(id) ON DELETE SET NULL,
    entity_type TEXT NULL,
    entity_id TEXT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_crm_events_created_at
    ON crm_events (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_crm_events_user_created_at
    ON crm_events (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_crm_events_type_created_at
    ON crm_events (event_type, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_crm_events_entity
    ON crm_events (entity_type, entity_id);

CREATE INDEX IF NOT EXISTS idx_crm_events_metadata_gin
    ON crm_events USING GIN (metadata);

ALTER TABLE crm_events ENABLE ROW LEVEL SECURITY;

-- Keep table server-oriented by default: service role can write/read, client reads can be added later if needed.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'crm_events'
          AND policyname = 'crm_events_service_role_all'
    ) THEN
        CREATE POLICY crm_events_service_role_all
            ON crm_events
            FOR ALL
            TO service_role
            USING (true)
            WITH CHECK (true);
    END IF;
END $$;
