-- Track meeting reschedules explicitly for forecast analytics

CREATE TABLE IF NOT EXISTS meeting_reschedule_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id UUID NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
    lead_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
    seller_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
    old_start_time TIMESTAMPTZ NOT NULL,
    new_start_time TIMESTAMPTZ NOT NULL,
    changed_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
    reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_meeting_reschedule_events_meeting
    ON meeting_reschedule_events (meeting_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_meeting_reschedule_events_lead
    ON meeting_reschedule_events (lead_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_meeting_reschedule_events_seller
    ON meeting_reschedule_events (seller_id, created_at DESC);

ALTER TABLE meeting_reschedule_events ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'meeting_reschedule_events'
          AND policyname = 'meeting_reschedule_events_service_role_all'
    ) THEN
        CREATE POLICY meeting_reschedule_events_service_role_all
            ON meeting_reschedule_events
            FOR ALL
            TO service_role
            USING (true)
            WITH CHECK (true);
    END IF;
END $$;
