-- DB-first CRM audit log (append-only) for reliable historical analysis.
-- Captures lead, meeting and forecast snapshot changes with before/after payloads.
-- This table is independent from crm_events to avoid breaking existing dashboards.

CREATE TABLE IF NOT EXISTS public.crm_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    actor_user_id UUID NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
    event_source TEXT NOT NULL DEFAULT 'db_trigger',
    before_data JSONB NULL,
    after_data JSONB NULL,
    context_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_crm_audit_log_created_at
    ON public.crm_audit_log (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_crm_audit_log_type_created_at
    ON public.crm_audit_log (event_type, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_crm_audit_log_entity
    ON public.crm_audit_log (entity_type, entity_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_crm_audit_log_actor_created_at
    ON public.crm_audit_log (actor_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_crm_audit_log_context_gin
    ON public.crm_audit_log USING GIN (context_data);

CREATE INDEX IF NOT EXISTS idx_crm_audit_log_before_gin
    ON public.crm_audit_log USING GIN (before_data);

CREATE INDEX IF NOT EXISTS idx_crm_audit_log_after_gin
    ON public.crm_audit_log USING GIN (after_data);

ALTER TABLE public.crm_audit_log ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'crm_audit_log'
          AND policyname = 'crm_audit_log_service_role_all'
    ) THEN
        CREATE POLICY crm_audit_log_service_role_all
            ON public.crm_audit_log
            FOR ALL
            TO service_role
            USING (true)
            WITH CHECK (true);
    END IF;
END $$;

CREATE OR REPLACE FUNCTION public.write_crm_audit_event(
    p_event_type TEXT,
    p_entity_type TEXT,
    p_entity_id TEXT,
    p_actor_user_id UUID DEFAULT NULL,
    p_before_data JSONB DEFAULT NULL,
    p_after_data JSONB DEFAULT NULL,
    p_context_data JSONB DEFAULT '{}'::jsonb,
    p_event_source TEXT DEFAULT 'db_trigger'
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NULLIF(TRIM(COALESCE(p_event_type, '')), '') IS NULL THEN
        RETURN;
    END IF;
    IF NULLIF(TRIM(COALESCE(p_entity_type, '')), '') IS NULL THEN
        RETURN;
    END IF;
    IF NULLIF(TRIM(COALESCE(p_entity_id, '')), '') IS NULL THEN
        RETURN;
    END IF;

    INSERT INTO public.crm_audit_log (
        event_type,
        entity_type,
        entity_id,
        actor_user_id,
        event_source,
        before_data,
        after_data,
        context_data
    )
    VALUES (
        TRIM(p_event_type),
        TRIM(p_entity_type),
        TRIM(p_entity_id),
        p_actor_user_id,
        COALESCE(NULLIF(TRIM(COALESCE(p_event_source, '')), ''), 'db_trigger'),
        p_before_data,
        p_after_data,
        COALESCE(p_context_data, '{}'::jsonb)
    );
EXCEPTION
    WHEN OTHERS THEN
        -- Keep business flows resilient; audit failures should not block writes.
        RAISE LOG 'write_crm_audit_event failed: %', SQLERRM;
END;
$$;

CREATE OR REPLACE FUNCTION public.crm_audit_lead_state(p_row public.clientes)
RETURNS JSONB
LANGUAGE sql
STABLE
AS $$
    SELECT jsonb_build_object(
        'id', p_row.id,
        'owner_id', p_row.owner_id,
        'owner_username', p_row.owner_username,
        'empresa_id', p_row.empresa_id,
        'etapa', p_row.etapa,
        'probabilidad', p_row.probabilidad,
        'value_forecast_estimated', p_row.value_forecast_estimated,
        'implementation_forecast_estimated', p_row.implementation_forecast_estimated,
        'forecast_close_date', COALESCE(p_row.close_date_forecast_estimated, p_row.forecast_close_date),
        'value_forecast_actual', p_row.value_forecast_actual,
        'implementation_forecast_actual', p_row.implementation_forecast_actual,
        'valor_real_cierre', p_row.valor_real_cierre,
        'valor_implementacion_real_cierre', p_row.valor_implementacion_real_cierre,
        'closed_at_real', p_row.closed_at_real,
        'probability_locked', p_row.probability_locked,
        'next_meeting_id', p_row.next_meeting_id,
        'last_snapshot_at', p_row.last_snapshot_at
    );
$$;

CREATE OR REPLACE FUNCTION public.crm_audit_meeting_state(p_row public.meetings)
RETURNS JSONB
LANGUAGE sql
STABLE
AS $$
    SELECT jsonb_build_object(
        'id', p_row.id,
        'lead_id', p_row.lead_id,
        'seller_id', p_row.seller_id,
        'meeting_sequence_number', p_row.meeting_sequence_number,
        'title', p_row.title,
        'start_time', p_row.start_time,
        'duration_minutes', p_row.duration_minutes,
        'meeting_type', p_row.meeting_type,
        'status', p_row.status,
        'meeting_status', p_row.meeting_status,
        'frozen_probability_value', p_row.frozen_probability_value,
        'confirmation_timestamp', p_row.confirmation_timestamp,
        'confirmed_by', p_row.confirmed_by,
        'not_held_reason_id', p_row.not_held_reason_id,
        'not_held_responsibility', p_row.not_held_responsibility
    );
$$;

CREATE OR REPLACE FUNCTION public.crm_audit_snapshot_state(p_row public.forecast_snapshots)
RETURNS JSONB
LANGUAGE sql
STABLE
AS $$
    SELECT jsonb_build_object(
        'id', p_row.id,
        'lead_id', p_row.lead_id,
        'seller_id', p_row.seller_id,
        'meeting_id', p_row.meeting_id,
        'snapshot_number', p_row.snapshot_number,
        'probability', p_row.probability,
        'forecast_value_amount', p_row.forecast_value_amount,
        'forecast_implementation_amount', p_row.forecast_implementation_amount,
        'forecast_close_date', p_row.forecast_close_date,
        'snapshot_timestamp', p_row.snapshot_timestamp,
        'source', p_row.source
    );
$$;

CREATE OR REPLACE FUNCTION public.trg_crm_audit_from_clientes()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_actor UUID;
    v_event_type TEXT;
    v_changed_fields TEXT[];
    v_is_stage_change BOOLEAN := FALSE;
    v_is_forecast_change BOOLEAN := FALSE;
    v_is_owner_change BOOLEAN := FALSE;
    v_new_stage_norm TEXT;
    v_is_new_stage_closed BOOLEAN := FALSE;
BEGIN
    IF TG_OP = 'INSERT' THEN
        v_actor := COALESCE(auth.uid(), NEW.owner_id);
        PERFORM public.write_crm_audit_event(
            'lead_created',
            'lead',
            NEW.id::TEXT,
            v_actor,
            NULL,
            public.crm_audit_lead_state(NEW),
            jsonb_build_object(
                'table', 'clientes',
                'operation', TG_OP
            )
        );
        RETURN NEW;
    END IF;

    IF TG_OP = 'DELETE' THEN
        v_actor := COALESCE(auth.uid(), OLD.owner_id);
        PERFORM public.write_crm_audit_event(
            'lead_deleted',
            'lead',
            OLD.id::TEXT,
            v_actor,
            public.crm_audit_lead_state(OLD),
            NULL,
            jsonb_build_object(
                'table', 'clientes',
                'operation', TG_OP
            )
        );
        RETURN OLD;
    END IF;

    v_actor := COALESCE(auth.uid(), NEW.owner_id, OLD.owner_id);

    v_is_stage_change := NEW.etapa IS DISTINCT FROM OLD.etapa;
    v_is_forecast_change := (
        NEW.probabilidad IS DISTINCT FROM OLD.probabilidad
        OR NEW.value_forecast_estimated IS DISTINCT FROM OLD.value_forecast_estimated
        OR NEW.implementation_forecast_estimated IS DISTINCT FROM OLD.implementation_forecast_estimated
        OR COALESCE(NEW.close_date_forecast_estimated, NEW.forecast_close_date) IS DISTINCT FROM COALESCE(OLD.close_date_forecast_estimated, OLD.forecast_close_date)
        OR NEW.probability_locked IS DISTINCT FROM OLD.probability_locked
        OR NEW.next_meeting_id IS DISTINCT FROM OLD.next_meeting_id
        OR NEW.last_snapshot_at IS DISTINCT FROM OLD.last_snapshot_at
    );
    v_is_owner_change := (
        NEW.owner_id IS DISTINCT FROM OLD.owner_id
        OR NEW.owner_username IS DISTINCT FROM OLD.owner_username
    );

    v_changed_fields := ARRAY_REMOVE(ARRAY[
        CASE WHEN NEW.etapa IS DISTINCT FROM OLD.etapa THEN 'etapa' END,
        CASE WHEN NEW.owner_id IS DISTINCT FROM OLD.owner_id THEN 'owner_id' END,
        CASE WHEN NEW.owner_username IS DISTINCT FROM OLD.owner_username THEN 'owner_username' END,
        CASE WHEN NEW.probabilidad IS DISTINCT FROM OLD.probabilidad THEN 'probabilidad' END,
        CASE WHEN NEW.value_forecast_estimated IS DISTINCT FROM OLD.value_forecast_estimated THEN 'value_forecast_estimated' END,
        CASE WHEN NEW.implementation_forecast_estimated IS DISTINCT FROM OLD.implementation_forecast_estimated THEN 'implementation_forecast_estimated' END,
        CASE WHEN COALESCE(NEW.close_date_forecast_estimated, NEW.forecast_close_date) IS DISTINCT FROM COALESCE(OLD.close_date_forecast_estimated, OLD.forecast_close_date) THEN 'forecast_close_date' END,
        CASE WHEN NEW.value_forecast_actual IS DISTINCT FROM OLD.value_forecast_actual THEN 'value_forecast_actual' END,
        CASE WHEN NEW.implementation_forecast_actual IS DISTINCT FROM OLD.implementation_forecast_actual THEN 'implementation_forecast_actual' END,
        CASE WHEN NEW.valor_real_cierre IS DISTINCT FROM OLD.valor_real_cierre THEN 'valor_real_cierre' END,
        CASE WHEN NEW.valor_implementacion_real_cierre IS DISTINCT FROM OLD.valor_implementacion_real_cierre THEN 'valor_implementacion_real_cierre' END,
        CASE WHEN NEW.closed_at_real IS DISTINCT FROM OLD.closed_at_real THEN 'closed_at_real' END,
        CASE WHEN NEW.probability_locked IS DISTINCT FROM OLD.probability_locked THEN 'probability_locked' END,
        CASE WHEN NEW.next_meeting_id IS DISTINCT FROM OLD.next_meeting_id THEN 'next_meeting_id' END,
        CASE WHEN NEW.last_snapshot_at IS DISTINCT FROM OLD.last_snapshot_at THEN 'last_snapshot_at' END
    ]::TEXT[], NULL::TEXT);

    IF COALESCE(array_length(v_changed_fields, 1), 0) = 0 THEN
        RETURN NEW;
    END IF;

    v_new_stage_norm := LOWER(TRIM(COALESCE(NEW.etapa, '')));
    v_is_new_stage_closed := v_new_stage_norm IN (
        'cerrado ganado',
        'cerrada ganada',
        'closed won',
        'won',
        'cerrado perdido',
        'cerrada perdida',
        'closed lost',
        'lost'
    );

    IF v_is_stage_change AND v_is_new_stage_closed THEN
        v_event_type := 'lead_closed';
    ELSIF v_is_stage_change THEN
        v_event_type := 'lead_stage_changed';
    ELSIF v_is_forecast_change THEN
        v_event_type := 'lead_forecast_updated';
    ELSIF v_is_owner_change THEN
        v_event_type := 'lead_reassigned';
    ELSE
        v_event_type := 'lead_updated';
    END IF;

    PERFORM public.write_crm_audit_event(
        v_event_type,
        'lead',
        NEW.id::TEXT,
        v_actor,
        public.crm_audit_lead_state(OLD),
        public.crm_audit_lead_state(NEW),
        jsonb_build_object(
            'table', 'clientes',
            'operation', TG_OP,
            'changed_fields', to_jsonb(v_changed_fields),
            'stage_change', v_is_stage_change,
            'forecast_change', v_is_forecast_change,
            'owner_change', v_is_owner_change
        )
    );

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_crm_audit_from_clientes ON public.clientes;
CREATE TRIGGER trg_crm_audit_from_clientes
AFTER INSERT OR UPDATE OR DELETE ON public.clientes
FOR EACH ROW
EXECUTE FUNCTION public.trg_crm_audit_from_clientes();

CREATE OR REPLACE FUNCTION public.trg_crm_audit_from_meetings()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_actor UUID;
    v_event_type TEXT;
    v_changed_fields TEXT[];
    v_new_status TEXT;
BEGIN
    IF TG_OP = 'INSERT' THEN
        v_actor := COALESCE(auth.uid(), NEW.seller_id);
        PERFORM public.write_crm_audit_event(
            'meeting_scheduled',
            'meeting',
            NEW.id::TEXT,
            v_actor,
            NULL,
            public.crm_audit_meeting_state(NEW),
            jsonb_build_object(
                'table', 'meetings',
                'operation', TG_OP
            )
        );
        RETURN NEW;
    END IF;

    IF TG_OP = 'DELETE' THEN
        v_actor := COALESCE(auth.uid(), OLD.confirmed_by, OLD.seller_id);
        PERFORM public.write_crm_audit_event(
            'meeting_deleted',
            'meeting',
            OLD.id::TEXT,
            v_actor,
            public.crm_audit_meeting_state(OLD),
            NULL,
            jsonb_build_object(
                'table', 'meetings',
                'operation', TG_OP
            )
        );
        RETURN OLD;
    END IF;

    v_actor := COALESCE(auth.uid(), NEW.confirmed_by, NEW.seller_id, OLD.confirmed_by, OLD.seller_id);

    v_changed_fields := ARRAY_REMOVE(ARRAY[
        CASE WHEN NEW.start_time IS DISTINCT FROM OLD.start_time THEN 'start_time' END,
        CASE WHEN NEW.duration_minutes IS DISTINCT FROM OLD.duration_minutes THEN 'duration_minutes' END,
        CASE WHEN NEW.meeting_type IS DISTINCT FROM OLD.meeting_type THEN 'meeting_type' END,
        CASE WHEN NEW.status IS DISTINCT FROM OLD.status THEN 'status' END,
        CASE WHEN NEW.meeting_status IS DISTINCT FROM OLD.meeting_status THEN 'meeting_status' END,
        CASE WHEN NEW.confirmation_timestamp IS DISTINCT FROM OLD.confirmation_timestamp THEN 'confirmation_timestamp' END,
        CASE WHEN NEW.confirmed_by IS DISTINCT FROM OLD.confirmed_by THEN 'confirmed_by' END,
        CASE WHEN NEW.not_held_reason_id IS DISTINCT FROM OLD.not_held_reason_id THEN 'not_held_reason_id' END,
        CASE WHEN NEW.not_held_responsibility IS DISTINCT FROM OLD.not_held_responsibility THEN 'not_held_responsibility' END,
        CASE WHEN NEW.primary_company_contact_id IS DISTINCT FROM OLD.primary_company_contact_id THEN 'primary_company_contact_id' END,
        CASE WHEN NEW.primary_company_contact_name IS DISTINCT FROM OLD.primary_company_contact_name THEN 'primary_company_contact_name' END,
        CASE WHEN NEW.attendees IS DISTINCT FROM OLD.attendees THEN 'attendees' END,
        CASE WHEN NEW.external_participants IS DISTINCT FROM OLD.external_participants THEN 'external_participants' END
    ]::TEXT[], NULL::TEXT);

    IF COALESCE(array_length(v_changed_fields, 1), 0) = 0 THEN
        RETURN NEW;
    END IF;

    v_new_status := LOWER(TRIM(COALESCE(NEW.meeting_status, '')));
    IF NEW.meeting_status IS DISTINCT FROM OLD.meeting_status AND v_new_status = 'held' THEN
        v_event_type := 'meeting_confirmed_held';
    ELSIF NEW.meeting_status IS DISTINCT FROM OLD.meeting_status AND v_new_status IN ('not_held', 'cancelled') THEN
        v_event_type := 'meeting_confirmed_not_held';
    ELSIF NEW.start_time IS DISTINCT FROM OLD.start_time
        OR NEW.duration_minutes IS DISTINCT FROM OLD.duration_minutes
        OR NEW.meeting_type IS DISTINCT FROM OLD.meeting_type THEN
        v_event_type := 'meeting_rescheduled';
    ELSE
        v_event_type := 'meeting_updated';
    END IF;

    PERFORM public.write_crm_audit_event(
        v_event_type,
        'meeting',
        NEW.id::TEXT,
        v_actor,
        public.crm_audit_meeting_state(OLD),
        public.crm_audit_meeting_state(NEW),
        jsonb_build_object(
            'table', 'meetings',
            'operation', TG_OP,
            'lead_id', NEW.lead_id,
            'seller_id', NEW.seller_id,
            'meeting_sequence_number', NEW.meeting_sequence_number,
            'changed_fields', to_jsonb(v_changed_fields)
        )
    );

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_crm_audit_from_meetings ON public.meetings;
CREATE TRIGGER trg_crm_audit_from_meetings
AFTER INSERT OR UPDATE OR DELETE ON public.meetings
FOR EACH ROW
EXECUTE FUNCTION public.trg_crm_audit_from_meetings();

CREATE OR REPLACE FUNCTION public.trg_crm_audit_from_forecast_snapshots()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_actor UUID;
    v_prev public.forecast_snapshots;
    v_delta_probability NUMERIC;
    v_delta_monthly NUMERIC;
    v_delta_implementation NUMERIC;
    v_delta_close_days INTEGER;
BEGIN
    v_actor := COALESCE(auth.uid(), NEW.seller_id);

    SELECT fs.*
    INTO v_prev
    FROM public.forecast_snapshots fs
    WHERE fs.lead_id = NEW.lead_id
      AND fs.id <> NEW.id
    ORDER BY fs.snapshot_number DESC, fs.created_at DESC
    LIMIT 1;

    IF FOUND THEN
        v_delta_probability := NEW.probability - COALESCE(v_prev.probability, 0);
        v_delta_monthly := COALESCE(NEW.forecast_value_amount, 0) - COALESCE(v_prev.forecast_value_amount, 0);
        v_delta_implementation := COALESCE(NEW.forecast_implementation_amount, 0) - COALESCE(v_prev.forecast_implementation_amount, 0);
        IF NEW.forecast_close_date IS NOT NULL AND v_prev.forecast_close_date IS NOT NULL THEN
            v_delta_close_days := (NEW.forecast_close_date::DATE - v_prev.forecast_close_date::DATE);
        END IF;
    END IF;

    PERFORM public.write_crm_audit_event(
        'forecast_snapshot_created',
        'forecast_snapshot',
        NEW.id::TEXT,
        v_actor,
        NULL,
        public.crm_audit_snapshot_state(NEW),
        jsonb_build_object(
            'table', 'forecast_snapshots',
            'operation', TG_OP,
            'lead_id', NEW.lead_id,
            'meeting_id', NEW.meeting_id,
            'seller_id', NEW.seller_id,
            'source', NEW.source,
            'previous_snapshot_id', COALESCE(v_prev.id, NULL),
            'delta_probability', v_delta_probability,
            'delta_forecast_value_amount', v_delta_monthly,
            'delta_forecast_implementation_amount', v_delta_implementation,
            'delta_forecast_close_date_days', v_delta_close_days
        )
    );

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_crm_audit_from_forecast_snapshots ON public.forecast_snapshots;
CREATE TRIGGER trg_crm_audit_from_forecast_snapshots
AFTER INSERT ON public.forecast_snapshots
FOR EACH ROW
EXECUTE FUNCTION public.trg_crm_audit_from_forecast_snapshots();

CREATE OR REPLACE VIEW public.crm_audit_log_latest_v AS
SELECT
    id,
    event_type,
    entity_type,
    entity_id,
    actor_user_id,
    event_source,
    before_data,
    after_data,
    context_data,
    created_at
FROM public.crm_audit_log
ORDER BY created_at DESC, id DESC;

