-- RUN THIS IN YOUR SUPABASE SQL EDITOR

-- 1. Check if 'asignado_a' exists in 'tareas', if not add it
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'tareas' AND column_name = 'asignado_a') THEN
        ALTER TABLE tareas ADD COLUMN asignado_a UUID REFERENCES auth.users(id);
    END IF;
END $$;

-- 2. Create 'historial_tareas' table if it doesn't exist
CREATE TABLE IF NOT EXISTS historial_tareas (
  id bigint generated by default as identity primary key,
  tarea_id bigint references tareas(id),
  user_id uuid references auth.users(id),
  titulo text not null,
  empresa text,
  fecha_completado timestamptz default now()
);

-- 3. Add 'tareas_completadas' to 'profiles' if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'tareas_completadas') THEN
         ALTER TABLE profiles ADD COLUMN tareas_completadas INTEGER DEFAULT 0;
    END IF;
END $$;
