-- RUN THIS SCRIPT TO ENABLE "ACTIVITY TYPES" AND "MODIFICATION TRACKING"

-- 1. Add 'tipo_actividad' column (if not exists)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'tareas' AND column_name = 'tipo_actividad') THEN
        ALTER TABLE tareas ADD COLUMN tipo_actividad TEXT DEFAULT 'Otro';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'historial_tareas' AND column_name = 'tipo_actividad') THEN
         ALTER TABLE historial_tareas ADD COLUMN tipo_actividad TEXT DEFAULT 'Otro';
    END IF;
END $$;

-- 2. Create 'historial_modificaciones_tareas' table
CREATE TABLE IF NOT EXISTS historial_modificaciones_tareas (
  id bigint generated by default as identity primary key,
  tarea_id bigint references tareas(id) ON DELETE CASCADE,
  user_id uuid references auth.users(id),
  campo_modificado text, -- 'fecha_vencimiento', 'titulo', 'tipo_actividad'
  valor_anterior text,
  valor_nuevo text,
  motivo text,
  origen_cambio text, -- 'Cliente', 'Interno', 'Otro'
  created_at timestamptz default now()
);

-- 3. Enable RLS (Row Level Security) for the new table
ALTER TABLE historial_modificaciones_tareas ENABLE ROW LEVEL SECURITY;

-- 4. Create Policy: Allow Authenticated Users to Insert and Read
CREATE POLICY "Enable read for authenticated users" ON "public"."historial_modificaciones_tareas"
AS PERMISSIVE FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Enable insert for authenticated users" ON "public"."historial_modificaciones_tareas"
AS PERMISSIVE FOR INSERT
TO authenticated
WITH CHECK (true);
